loop_hz: 10.0
discover_hz: 1.0

default_hp: 100
default_ammo: 50.0
fire_range: 3.0
hit_width: 0.1
fire_damage: 5
vision_range: 2.0

fov_deg: 120.0
map_topic: "/map"
occ_threshold: 50
block_unknown: true